### ISSUE TITLE
job control doesn't work

### ISSUE THREAD

**Issue by romkatv** [xxh/zsh-portable#1]
To reproduce:

1. Start zsh from zsh-portable.
```zsh
mkdir /tmp/zsh-portable
cd /tmp/zsh-portable
curl -fsSL https://github.com/xxh/zsh-portable/raw/master/result/zsh-portable-Linux-x86_64.tar.gz | tar -pxz
./zsh.sh
```
2. Type `setopt monitor`.

- Expected: no error.
- Actual: error on step 2: `setopt: can't change option: monitor`.

Job control appears to be disabled by `--without-tcsetpgrp` in https://github.com/xxh/zsh-portable/blob/master/Dockerfile.

**Comment by anki-code** [comment]
Hey @romkatv! Thank you for the report! I've rebuilt the image. Could you please try again?

If you're using xxh:
```
xxhp ri xxh-shell-zsh
xxh myhost +s zsh +if
setopt monitor
```

**Comment by romkatv** [comment]
Thanks! The error is gone.

**Comment by anki-code** [comment]
I've did the trick. A bit hacky but it works. Try:
```
mkdir /tmp/zsh-portable
cd /tmp/zsh-portable
curl -fsSL https://github.com/xxh/zsh-portable/raw/master/result/zsh-portable-musl-Linux-x86_64.tar.gz | tar -pxz
./zsh.sh
```
It works for me on ubuntu and alpine like a charm )
