### ISSUE TITLE
[feature request] link zsh statically to make it portable

### ISSUE THREAD

**Issue by romkatv** [xxh/zsh-portable#2]
To reproduce:

1. Install zsh-portable.
```zsh
mkdir /tmp/zsh-portable
cd /tmp/zsh-portable
curl -fsSL https://github.com/xxh/zsh-portable/raw/master/result/zsh-portable-Linux-x86_64.tar.gz | tar -pxz
```
2. Type `ldd zsh`.

- Expected: statically linked binary.
- Actual: dynamically linked binary with a dependency on glibc.

This makes the binary usable only on systems with a compatible version of glibc. On systems without glibc (e.g., Alpine or Android), zsh-portable doesn't work.

Would it be possible to create a statically-linked binary, perhaps linked against musl?

---------------
Solutions:
🥇 https://github.com/xxh/zsh-portable/issues/2#issuecomment-599801018
🥉 https://github.com/xxh/zsh-portable/issues/2#issuecomment-599216563

**Comment by anki-code** [comment]
Good questions)

1. About glibc. Because it has backward compatibility there is a common solution: just building the binary on most earlier version of linux. For example AppImage for python uses glibc 2.17 from manylinux 2010 and it will work on any linux with glibc after 2010. For Zsh building I used here Ubuntu 14 has glibc 2.19 and looks enough.

2. About musl. I've tried to build zsh on Alpine. It could be achieved by replacing Ubuntu to Alpine and replace ubuntu apt to alpine apk commands in the Dockerfile. As result I got zsh with musl just for interest. No commits about it.

**Comment by romkatv** [comment]
I mentioned musl not because I want the dependency on musl to be replaced by a dependency on glibc but because with musl it's easier to create a statically linked binary. With glibc it's generally impossible (although in some cases you can do it).

**Comment by anki-code** [comment]
I haven't experience with musl and if you could create musl version PR is very welcome. I tried once and it was looking as working way.

**Comment by romkatv** [comment]
I'm not interested in a binary with a dependency on musl. I'm asking if it's possible to create a statically linked binary to make it portable.

**Comment by anki-code** [comment]
Could you please give an example of OS (and version) with glibc>=2.19 where it's not working? I could be use it for testing.

**Comment by romkatv** [comment]
Alpine Linux

**Comment by romkatv** [comment]
If you can build a binary that works on Alpine and Ubuntu, it'll work pretty much on any Linux.

**Comment by anki-code** [comment]
Added alpine version:
* `Dockerfile-alpine`
* `build-alpine.sh`
* `zsh-portable-alpine-Linux-x86_64.tar.gz`

And in Ubuntu it woks if add musl to `lib`:
```
# Ubuntu
mkdir /tmp/zsh-portable
cd /tmp/zsh-portable
curl -fsSL https://github.com/xxh/zsh-portable/raw/master/result/zsh-portable-alpine-Linux-x86_64.tar.gz | tar -pxz
cp libc.musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
./zsh.sh
```
The question is: how to avoid `cp libc.musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1`?

**Comment by romkatv** [comment]
> The question is: how to avoid `cp libc.musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1`?

You need to find a way to link `zsh` binary statically.

You use powerlevel10k, right? In the powerlevel10k directory there is `gitstatus/bin/gitstatusd-linux-x86_64-static`. You can copy this binary to Ubuntu or Alpine and run it. It'll just work. This is because it's statically linked. If you run `ldd` on it, it'll tell you as much. Compare it with the result of `ldd` on `gitstatusd-linux-x86_64`.

**Comment by anki-code** [comment]
I've did the trick. A bit hacky but it works. Try `zsh-portable-musl-Linux-x86_64.tar.gz`:
```
mkdir /tmp/zsh-portable
cd /tmp/zsh-portable
curl -fsSL https://github.com/xxh/zsh-portable/raw/master/result/zsh-portable-musl-alpine-portable-Linux-x86_64.tar.gz | tar -pxz
./zsh.sh
```
It works for me on ubuntu and alpine like a charm )
If it works for you as expected I'm going to use this for xxh.

**Comment by anki-code** [comment]
If it works for you as expected I'm going to use this for xxh.

**Comment by romkatv** [comment]
Have you tried building a statically linked zsh binary?

**Comment by anki-code** [comment]
Sad but I'm not so experienced in building static binaries. I've tried to rebuild with `--enable-libc-musl` (help says `compile with musl as the C library`) and the `zsh` binary has grown like it includes libc/musl. But no changes while trying execution.

As result I just replace `/lib/musl` to `.////musl` in the `zsh` binary and it works. I can't catch up any side effects.

**Comment by romkatv** [comment]
> As result I just replace `/lib/musl` to `.////musl` and it works.

Yeah, I saw that. This isn't what I would like to have. Shipping dynamic libraries with executables can work OK if you use chroot or similar. Otherwise it's prone to clashes.

> I've tried to rebuild with `--enable-libc-musl`

This doesn't seem like the right flag.

When I get some free time, I'll see if it's not too hard to build a static binary.

**Comment by romkatv** [comment]
FYI: I've used zsh-portable without xxh: https://www.reddit.com/r/zsh/comments/fiq9w2/bring_zsh_with_ohmyzsh_wherever_you_go_through/fkka097/. Works very well.

**Comment by romkatv** [comment]
Took a shot at it. The build process is very hacky but the result is robust and works very well. See https://github.com/romkatv/zsh-bin. If you try this, please let me know whether it works for you.

There are a couple things that could be improved.

1. There is no way to create global and `zshenv` and `zshrc`. This isn't a big deal because the binary is supposed to be installed in a home directory, so global rcs are unnecessary. Nevertheless, it would be nice to support them. It's fairly easy to do but I just ran out of time.
2. I've built man pages for Zsh and included them in the archive, but they don't get picked up. I haven't looked at what it would take to make `man zsh` work.

> xxh deleted a comment from romkatv yesterday

I really don't like when things I post publicly get deleted.

**Comment by romkatv** [comment]
Feel free to close this issue as I no longer need this feature.

If you want, you are welcome to use any part of https://github.com/romkatv/zsh-bin. No attribution necessary.

**Comment by anki-code** [comment]
Thank you! You rock again! I'm reviewing it now!

> I really don't like when things I post publicly get deleted.

Sorry.

> No attribution necessary.

Hah, because:

> magic marker, trailing p10k totally accidental

We all want a bit of attention :)

**Comment by anki-code** [comment]
> In March of 2020 an announcement was posted on /r/zsh. It mentioned that "xxh uses the portable version of Zsh". I thought it would be cool to migrate my ssh.bash script to Zsh and install the portable version of Zsh on the remote machine if there isn't one already installed (this is basically what xxh does).

Thank you! It's appreciated. I think that open source projects name-dropping is good for ecosystem.

You can see "Thanks" part of xxh README and you will be there soon :)

**Comment by romkatv** [comment]
My pleasure :wink:

**Comment by anki-code** [comment]
> Took a shot at it. The build process is very hacky but the result is robust and works very well. See https://github.com/romkatv/zsh-bin. If you try this, please let me know whether it works for you.

It completely works. Thanks! I'm going to create `xxh-shell-zsh-<romkasuper/p10k/zsh-bin please choose>` and testing it with xxh.

> There is no way to create global and zshenv and zshrc.

I read this as feature not bug )

**Comment by romkatv** [comment]
> It completely works.

Thanks for the confirmation!

> I'm going to create `xxh-shell-zsh-<romkasuper/p10k/zsh-bin please choose>` and testing it with xxh.

🤣

**Comment by anki-code** [comment]
Done:
```
pip install --upgrade xxh-xxh # to xxh 0.6.1
xxhp install xxh-shell-zsh-romkatv xxh-plugin-zsh-powerlevel10k
xxh myhost +s xxh-shell-zsh-romkatv +if +q
```
Added to [Thanks](https://github.com/xxh/xxh#thanks) 👍
